baseURL = "https://marcopizzolato.com/"
languageCode = "en-us"
title = "Marco Pizzolato Portfolio"
theme = "mediumish-gohugo-theme"
summaryLength = 25
DefaultContentLanguage = "en"
copyright = "Marco Pizzolato - All rights reserved"
enableEmoji = true
publishDir = "public_web"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$","\\.knit\\.md$", "\\.utf8\\.md$"]
#disqusShortname = "your-shortname-here"
googleAnalytics = "UA-132680808-1"

[permalinks]
    post = "/:year/:month/:day/:slug/"

[markup.goldmark.renderer]
unsafe= true

# This refers to Site.Params
[params]
  logo = "/images/portfolio-02.png"
  logo2 = "/images/rocket_01.png"
  description ="This is the porfolio of Marco Pizzolato" #description of the website for the search engines
  #mailchimp = "you can provide a mailchimp-link here"
  useFontAwesome = true
  avatar = ""
  bib_style = "IEEE" # IEEE, APA, else


[params.author] # Line with the author face-mane
  name = "Marco Pizzolato"
  thumbnail = "/images/marco_prof_3.jpg"
  description = "Creator of this blog."
  
[params.index]
  picture = "./images/marcopizzo.jpg"
  title = "Marco Pizzolato"
  subtitle = "Geospatial Data Scientist"
  mdtext = '''
</br>
<p style="font-size: 23px;"><b>Welcome to my personal website!</b></p>
<p style="font-size: 20px;">This space is a collection of some data explorations and works I have completed while in South Sudan responding to the humanitarian crisis, during my MSc in GIS at the University of Edinburgh and in my free time.<p>
</br>
<p style="font-size: 23px;"><b>A little about me...</b></p>
<p style="font-size: 20px;">Dynamic and energetic I am very passionate about the projects I get involved in.   
I am always looking for new projects to embark on, which will challenge my brain bringing out my inventiveness, creativity and imagination to find the best solution. Strongly believing that <i>“Together we stand, alone we fall”</i> I always collaborate in a profitable way with my team members, often building over time strong friendships. </p> 
</br>
Happy exploring and get in touch if you want to know more!
</br>
</br>
<b><a href="http://www.marcopizzolato.com">- Projects - </a></b><b><a href="http://www.marcopizzolato.com/curriculum/vitae/"> - Curiculum -</a></b>
</br>
</br>
</br>
'''

alertbar = false

[params.social]
 github = "marcopizzolato-mp"
 linkedin = "pizzolatomarco"
 pdf = "file/d/16nn7L30nMfCIKSLkRq1Sbh7QR76H-Frk/view?usp=sharing"
 mail = "contact@marcopizzolato.com"
  # xing = "<username>"
  # medium = "<username>"

## Main Menu
[[menu.main]]
    name = "homepage" # This is the name in the menu
    weight = 100
    identifier = "projects"
    url = "/"
    
[[menu.main]]
    name = "About Me"
    identifier = "about_bio"
    weight = 300
    url = "/about/bio"
    
[[menu.main]]
    name = "curriculum"
    identifier = "curriculum_vitae"
    weight = 200
    url = "/curriculum/vitae"


[params.display]
experience = true
education = true
languages = true
awards = true
skills = false
skills_grouped = true
interests = false
contact = false
linkedin = false
tagline = true
aboutMe = false
projects = false
publications = false
certificates = false
avatar = false

[params.title_as]
experience = "Experience"
education = "Education"
languages = "Languages"
awards = "Awards"
skills = "Skills"
certificates = "Certifications"
interests = "Interests"
about_me = "About Me"
publications = "Publications"
projects = "Projects"

[params.display.footer]
footer = true
links = false
credits = false

[params.footer]
footnote = "You can print this resume in or save as pdf directly from the browser - Last update on May 2021."

[params.footer.links]
[[params.footer.links.link]]
prefix = "Contact me on"
name = "Linkedin"
url = "https://linkedin.com/in/mertbakir/"
icon = "fab fa-linkedin"

[[params.footer.links.link]]
prefix = "Check out my"
name = "Website"
url = "https://mertbakir.gitlab.io/about/"
icon = "fas fa-globe"